app = "helbling-rapporte-qanzhw"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  GOOGLE_SERVICE_ACCOUNT_FILE = "./credentials/service-account.json"
  UPLOADS_DIR = "/app/db/uploads"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "rapporte_data"
  destination = "/app/db"
  initial_size = "1gb"
